language: perl
perl:
  - 5.10
  - 5.12
  - 5.14
  - 5.16
before_install:
  - "git clone git://github.com/hcatlin/libsass.git /tmp/libsass"
  - "pushd /tmp/libsass && ./configure && make && sudo make install && popd"
install:
  - "cpanm --installdeps --notest . || cat ~/.cpanm/build.log"
after_failure: 
  - "cat ~/.cpanm/build.log"
