language: perl
perl:
  - 5.10
  - 5.12
  - 5.14
  - 5.16
before_install:
  - "git clone git://github.com/hcatlin/libsass.git"
  - "cd libsass && ./configure && make && sudo make install"
script:
  - "cpanm --installdeps --notest ."
after_failure: 
  - "cat ~/.cpanm/build.log"
